// Code generated by MCHP Chatbot
import { Response } from "express";
import { AuthRequest } from "../middleware/auth";
import { TaskService } from "../services";
import { CreateTaskSchema, UpdateTaskSchema } from "@iqoo/shared";
import { AppError } from "../middleware/errorHandler";
import { calculateDeadlineRisk } from "../productivity/prioritizer";

export class TaskController {
  constructor(private taskService: TaskService) {}

  async createTask(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");

    const input = CreateTaskSchema.parse(req.body);
    const task = await this.taskService.createTask(req.userId, input);

    res.status(201).json({
      success: true,
      data: { task },
    });
  }

  async getTask(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");

    const { id } = req.params;
    const task = await this.taskService.getTask(id, req.userId);

    if (!task) {
      throw new AppError(404, "Task not found", "TASK_NOT_FOUND");
    }

    res.json({
      success: true,
      data: { task },
    });
  }

  async listTasks(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");

    const { projectId, status } = req.query;
    const tasks = await this.taskService.getTasks(req.userId, {
      projectId: projectId as string,
      status: status as any,
    });

    res.json({
      success: true,
      data: { tasks },
    });
  }

  async updateTask(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");

    const { id } = req.params;
    const input = UpdateTaskSchema.parse(req.body);
    const task = await this.taskService.updateTask(id, req.userId, input);

    res.json({
      success: true,
      data: { task },
    });
  }

  async deleteTask(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");

    const { id } = req.params;
    await this.taskService.deleteTask(id, req.userId);

    res.json({
      success: true,
      message: "Task deleted",
    });
  }

  async completeTask(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");

    const { id } = req.params;
    const { actualMinutes } = req.body;
    const task = await this.taskService.completeTask(id, req.userId, actualMinutes);

    res.json({
      success: true,
      data: { task },
    });
  }

  async getTaskRisk(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");
    const { id } = req.params;
    const task = await this.taskService.getTask(id, req.userId);
    if (!task) throw new AppError(404, "Task not found", "TASK_NOT_FOUND");

    const blockers = await this.taskService.getTasksBlocking(id, req.userId);
    const unfinishedDependencies = blockers.filter((b: any) => b.status !== "COMPLETED").length;
    const overdue = task.deadline ? new Date(task.deadline) < new Date() : false;

    const risk = calculateDeadlineRisk({
      deadline: task.deadline ? new Date(task.deadline) : undefined,
      estimatedMinutes: task.estimatedMinutes ?? undefined,
      status: task.status,
      dependencies: blockers.map((b: any) => b.id),
      unfinishedDependencies,
      overdue,
    });
    res.json({ success: true, data: { risk } });
  }

  async getDependencyInfo(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");
    const { id } = req.params;
    const task = await this.taskService.getTask(id, req.userId);
    if (!task) throw new AppError(404, "Task not found", "TASK_NOT_FOUND");

    const blocking = await this.taskService.getTasksBlockedBy(id, req.userId);
    const blockedBy = await this.taskService.getTasksBlocking(id, req.userId);
    res.json({ success: true, data: { blocking, blockedBy } });
  }

  async createDependency(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");
    const { fromTaskId, toTaskId } = req.body;
    if (!fromTaskId || !toTaskId) {
      throw new AppError(400, "fromTaskId and toTaskId are required", "MISSING_PARAMS");
    }
    const dep = await this.taskService.createDependency(fromTaskId, toTaskId, req.userId);
    res.status(201).json({ success: true, data: { dependency: dep } });
  }

  async deleteDependency(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");
    const { fromTaskId, toTaskId } = req.body;
    if (!fromTaskId || !toTaskId) {
      throw new AppError(400, "fromTaskId and toTaskId are required", "MISSING_PARAMS");
    }
    await this.taskService.deleteDependency(fromTaskId, toTaskId, req.userId);
    res.json({ success: true, message: "Dependency removed" });
  }

  async listDependencies(req: AuthRequest, res: Response) {
    if (!req.userId) throw new AppError(401, "Not authenticated", "NOT_AUTHENTICATED");
    const dependencies = await this.taskService.getDependencies(req.userId);
    res.json({ success: true, data: { dependencies } });
  }
}


