// Code generated by MCHP Chatbot
import { TaskPriority } from "@iqoo/shared";

interface TaskScoreFactors {
  deadline?: Date;
  priority: TaskPriority;
  estimatedMinutes?: number;
  isOverdue: boolean;
  hasDependencies: boolean;
  isBlocked: boolean;
}

export const calculateTaskPriority = (
  factors: TaskScoreFactors
): {
  priority: TaskPriority;
  score: number;
} => {
  let score = 0;

  // Deadline proximity (0-30 points)
  if (factors.deadline) {
    const now = new Date();
    const daysUntilDeadline =
      (factors.deadline.getTime() - now.getTime()) / (1000 * 60 * 60 * 24);

    if (daysUntilDeadline < 0) {
      score += 30; // Overdue
    } else if (daysUntilDeadline === 0) {
      score += 28; // Today
    } else if (daysUntilDeadline <= 1) {
      score += 25; // Tomorrow
    } else if (daysUntilDeadline <= 3) {
      score += 18; // Within 3 days
    } else if (daysUntilDeadline <= 7) {
      score += 10; // Within a week
    } else {
      score += 5; // More than a week
    }
  }

  // Base priority (0-25 points)
  switch (factors.priority) {
    case TaskPriority.CRITICAL:
      score += 25;
      break;
    case TaskPriority.HIGH:
      score += 18;
      break;
    case TaskPriority.MEDIUM:
      score += 10;
      break;
    case TaskPriority.LOW:
      score += 3;
      break;
  }

  // Effort estimate (0-15 points) - smaller tasks get bonus
  if (factors.estimatedMinutes) {
    if (factors.estimatedMinutes <= 15) {
      score += 15; // Quick wins
    } else if (factors.estimatedMinutes <= 30) {
      score += 12;
    } else if (factors.estimatedMinutes <= 60) {
      score += 8;
    } else {
      score += 4; // Large tasks penalized slightly
    }
  }

  // Overdue status (0-15 points)
  if (factors.isOverdue) {
    score += 15;
  }

  // Dependencies (+10 for blocking, -5 for blocked)
  if (factors.hasDependencies && !factors.isBlocked) {
    score += 10; // Tasks others depend on
  }
  if (factors.isBlocked) {
    score -= 5; // Blocked tasks get penalized
  }

  // Determine final priority based on score
  let finalPriority: TaskPriority;
  if (score >= 60) {
    finalPriority = TaskPriority.CRITICAL;
  } else if (score >= 40) {
    finalPriority = TaskPriority.HIGH;
  } else if (score >= 20) {
    finalPriority = TaskPriority.MEDIUM;
  } else {
    finalPriority = TaskPriority.LOW;
  }

  return {
    priority: finalPriority,
    score: Math.min(score, 100),
  };
};









/**
 * Deadline risk estimation, returns { level, score, explanation }
 */
export function calculateDeadlineRisk({
  deadline,
  estimatedMinutes = 60,
  status: _status,
  dependencies = [],
  unfinishedDependencies = 0,
  overdue,
}: {
  deadline?: Date;
  estimatedMinutes?: number;
  status?: string;
  dependencies?: string[];
  unfinishedDependencies?: number;
  overdue?: boolean;
}): { riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; score: number; explanation: string } {
  let score = 0;
  const now = new Date();
  let timeUntilDeadlineHrs = 24 * 365; // default: far future
  let explainArr = [];

  if (deadline) {
    timeUntilDeadlineHrs = (deadline.getTime() - now.getTime()) / (1000 * 60 * 60);
    if (timeUntilDeadlineHrs < 0) {
      score += 40;
      explainArr.push("Deadline has passed.");
    } else if (timeUntilDeadlineHrs < 24) {
      score += 32;
      explainArr.push("Deadline within 24 hours.");
    } else if (timeUntilDeadlineHrs < 72) {
      score += 24;
      explainArr.push("Deadline this week.");
    } else {
      score += 10;
      explainArr.push("Deadline is not imminent.");
    }
  } else {
    explainArr.push("No deadline set.");
    score += 5;
  }

  // Effort to remaining time ratio
  if (estimatedMinutes) {
    const estHrs = estimatedMinutes / 60;
    if (deadline && timeUntilDeadlineHrs > 0) {
      const ratio = estHrs / timeUntilDeadlineHrs;
      if (ratio > 2) {
        score += 35;
        explainArr.push(`${estHrs.toFixed(1)}h estimated, only ${timeUntilDeadlineHrs.toFixed(1)}h left.`);
      } else if (ratio > 1) {
        score += 22;
        explainArr.push(`${estHrs.toFixed(1)}h estimated, time is tight.`);
      } else if (ratio > 0.5) {
        score += 10;
        explainArr.push(`Estimated time is significant (${estHrs.toFixed(1)}h).`);
      } else {
        score += 3;
        explainArr.push(`Estimated to be manageable.`);
      }
    }
  }

  // Blockers and dependencies
  if (unfinishedDependencies && unfinishedDependencies > 0) {
    score += 14;
    explainArr.push(`Blocked by ${unfinishedDependencies} unfinished dependent tasks.`);
  } else if (dependencies && dependencies.length > 0) {
    explainArr.push("Has dependencies but none are blocking.");
  }

  if (overdue) {
    score += 15;
    explainArr.push("Task is overdue.");
  }

  let riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" = "LOW";
  if (score >= 70) riskLevel = "CRITICAL";
  else if (score >= 45) riskLevel = "HIGH";
  else if (score >= 25) riskLevel = "MEDIUM";

  return {
    riskLevel,
    score: Math.min(100, score),
    explanation: explainArr.join(' '),
  };
}
















export const sortTasksByPriority = (
  tasks: Array<{ priority: TaskPriority; deadline?: Date; isOverdue: boolean }>
): Array<{ priority: TaskPriority; deadline?: Date; isOverdue: boolean }> => {
  const priorityOrder = {
    [TaskPriority.CRITICAL]: 0,
    [TaskPriority.HIGH]: 1,
    [TaskPriority.MEDIUM]: 2,
    [TaskPriority.LOW]: 3,
  };

  return tasks.sort((a, b) => {
    if (a.isOverdue && !b.isOverdue) return -1;
    if (!a.isOverdue && b.isOverdue) return 1;

    const priorityDiff =
      priorityOrder[a.priority] - priorityOrder[b.priority];
    if (priorityDiff !== 0) return priorityDiff;

    if (a.deadline && b.deadline) {
      return a.deadline.getTime() - b.deadline.getTime();
    }

    return 0;
  });
};