// Code generated by MCHP Chatbot
import { prisma } from "./prisma";
import { CreateTaskInput, UpdateTaskInput, TaskStatus } from "@iqoo/shared";

function serializeTags(tags?: string[] | string) {
  if (Array.isArray(tags)) return JSON.stringify(tags);
  if (typeof tags === "string") return tags;
  return "[]";
}

function parseTags(tags: unknown): string[] {
  if (Array.isArray(tags)) return tags as string[];
  if (typeof tags === "string") {
    try {
      const parsed = JSON.parse(tags);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return tags ? [tags] : [];
    }
  }
  return [];
}

function mapTask<T extends { tags?: unknown }>(task: T) {
  return { ...task, tags: parseTags(task.tags) };
}

export class TaskRepository {
  async findById(id: string, userId: string) {
    const task = await prisma.task.findFirst({
      where: {
        id,
        userId,
      },
      include: {
        reminders: true,
        focusSessions: true,
        dependsOn: {
          include: { toTask: true },
        },
        blockedBy: {
          include: { fromTask: true },
        },
      },
    });
    return task ? mapTask(task) : null;
  }

  async findByUserId(userId: string, options?: { projectId?: string; status?: TaskStatus }) {
    const tasks = await prisma.task.findMany({
      where: {
        userId,
        ...(options?.projectId && { projectId: options.projectId }),
        ...(options?.status && { status: options.status }),
      },
      include: {
        reminders: true,
        dependsOn: {
          include: { toTask: true },
        },
        blockedBy: {
          include: { fromTask: true },
        },
      },
      orderBy: [{ priority: "desc" }, { deadline: "asc" }],
    });
    return tasks.map(mapTask);
  }

  async create(userId: string, data: CreateTaskInput) {
    const { tags, dependencies, ...rest } = data;
    const task = await prisma.task.create({
      data: {
        userId,
        ...rest,
        tags: serializeTags(tags),
      },
    });

    if (Array.isArray(dependencies) && dependencies.length > 0) {
      for (const depTaskId of dependencies) {
        // depTaskId is a prerequisite that blocks the new task
        await prisma.taskDependency.upsert({
          where: {
            fromTaskId_toTaskId: {
              fromTaskId: depTaskId,
              toTaskId: task.id,
            },
          },
          update: {},
          create: {
            fromTaskId: depTaskId,
            toTaskId: task.id,
          },
        }).catch(() => {});
      }
    }

    return mapTask(task);
  }

  async update(id: string, userId: string, data: UpdateTaskInput) {
    const { tags, dependencies, ...rest } = data;
    const task = await prisma.task.update({
      where: {
        id,
        userId,
      },
      data: {
        ...rest,
        ...(tags !== undefined ? { tags: serializeTags(tags) } : {}),
      },
      include: {
        reminders: true,
        dependsOn: true,
        blockedBy: true,
      },
    });

    if (Array.isArray(dependencies)) {
      // Clear previous dependencies where this task is blocked and set new ones
      await prisma.taskDependency.deleteMany({
        where: { toTaskId: id },
      });
      for (const depTaskId of dependencies) {
        if (depTaskId !== id) {
          await prisma.taskDependency.upsert({
            where: {
              fromTaskId_toTaskId: {
                fromTaskId: depTaskId,
                toTaskId: id,
              },
            },
            update: {},
            create: {
              fromTaskId: depTaskId,
              toTaskId: id,
            },
          }).catch(() => {});
        }
      }
    }

    return mapTask(task);
  }

  async delete(id: string, userId: string) {
    return prisma.task.delete({
      where: {
        id,
        userId,
      },
    });
  }

  async getTasksWithBlockers(userId: string) {
    const tasks = await prisma.task.findMany({
      where: { userId },
      include: {
        blockedBy: {
          include: { fromTask: true },
        },
        dependsOn: {
          include: { toTask: true },
        },
      },
    });

    return tasks.map((task) => ({
      ...mapTask(task),
      isBlocked: task.blockedBy.some((dep) => dep.fromTask.status !== "COMPLETED"),
    }));
  }

  // Returns all tasks that THIS task blocks (tasks downstream)
  async findTasksBlockedBy(taskId: string, userId: string) {
    const deps = await prisma.taskDependency.findMany({
      where: { fromTaskId: taskId },
      include: { toTask: true },
    });
    return deps
      .map((dep) => dep.toTask)
      .filter((t) => t && t.userId === userId)
      .map(mapTask);
  }

  // Returns all tasks that block THIS task (tasks upstream)
  async findTasksBlocking(taskId: string, userId: string) {
    const deps = await prisma.taskDependency.findMany({
      where: { toTaskId: taskId },
      include: { fromTask: true },
    });
    return deps
      .map((dep) => dep.fromTask)
      .filter((t) => t && t.userId === userId)
      .map(mapTask);
  }

  async createDependency(fromTaskId: string, toTaskId: string, userId: string) {
    // verify both tasks belong to user
    const [fromTask, toTask] = await Promise.all([
      prisma.task.findFirst({ where: { id: fromTaskId, userId } }),
      prisma.task.findFirst({ where: { id: toTaskId, userId } }),
    ]);
    if (!fromTask || !toTask) {
      throw new Error("One or both tasks not found");
    }
    if (fromTaskId === toTaskId) {
      throw new Error("A task cannot depend on itself");
    }

    return prisma.taskDependency.upsert({
      where: {
        fromTaskId_toTaskId: {
          fromTaskId,
          toTaskId,
        },
      },
      update: {},
      create: {
        fromTaskId,
        toTaskId,
      },
      include: {
        fromTask: true,
        toTask: true,
      },
    });
  }

  async deleteDependency(fromTaskId: string, toTaskId: string, userId: string) {
    const dep = await prisma.taskDependency.findFirst({
      where: {
        fromTaskId,
        toTaskId,
        fromTask: { userId },
      },
    });
    if (!dep) {
      return null;
    }
    return prisma.taskDependency.delete({
      where: { id: dep.id },
    });
  }

  async findDependencies(userId: string) {
    return prisma.taskDependency.findMany({
      where: {
        fromTask: { userId },
      },
      include: {
        fromTask: true,
        toTask: true,
      },
    });
  }
}


export class ProjectRepository {
  async create(userId: string, data: { name: string; description?: string; color?: string }) {
    const existing = await prisma.project.findFirst({
      where: { userId, name: data.name },
    });
    if (existing) {
      return prisma.project.update({
        where: { id: existing.id },
        data: {
          description: data.description || existing.description,
          color: data.color || existing.color,
        },
      });
    }
    return prisma.project.create({
      data: {
        userId,
        ...data,
      },
    });
  }

  async findById(id: string, userId: string) {
    return prisma.project.findFirst({
      where: { id, userId },
      include: {
        tasks: {
          include: {
            blockedBy: {
              include: { fromTask: { select: { id: true, title: true, status: true } } },
            },
            dependsOn: {
              include: { toTask: { select: { id: true, title: true, status: true } } },
            },
          },
        },
      },
    });
  }

  async findByUserId(userId: string) {
    return prisma.project.findMany({
      where: { userId },
      include: {
        tasks: {
          select: {
            id: true,
            status: true,
            priority: true,
            deadline: true,
            estimatedMinutes: true,
          },
        },
      },
    });
  }

  async update(id: string, userId: string, data: any) {
    return prisma.project.update({
      where: { id, userId },
      data,
      include: { tasks: true },
    });
  }

  async delete(id: string, userId: string) {
    return prisma.project.delete({
      where: { id, userId },
    });
  }
}

function mapInboxItem(item: any) {
  if (!item) return item;
  let extracted = item.extractedData;
  if (typeof extracted === "string") {
    try {
      extracted = JSON.parse(extracted);
    } catch {
      extracted = {};
    }
  }
  return {
    ...item,
    extractedData: extracted || {},
  };
}

export class ActionInboxRepository {
  async create(userId: string, data: any) {
    const { extractedData, ...rest } = data;
    const item = await prisma.actionInboxItem.create({
      data: {
        userId,
        ...rest,
        extractedData:
          extractedData == null
            ? "{}"
            : typeof extractedData === "string"
              ? extractedData
              : JSON.stringify(extractedData),
      },
    });
    return mapInboxItem(item);
  }

  async findByUserId(userId: string) {
    const items = await prisma.actionInboxItem.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
    });
    return items.map(mapInboxItem);
  }

  async findById(id: string, userId: string) {
    const item = await prisma.actionInboxItem.findFirst({
      where: { id, userId },
    });
    return mapInboxItem(item);
  }

  async update(id: string, userId: string, data: any) {
    const { extractedData, ...rest } = data;
    const updateData: any = { ...rest };
    if (extractedData !== undefined) {
      updateData.extractedData =
        typeof extractedData === "string"
          ? extractedData
          : JSON.stringify(extractedData);
    }
    const item = await prisma.actionInboxItem.update({
      where: { id, userId },
      data: updateData,
    });
    return mapInboxItem(item);
  }

  async delete(id: string, userId: string) {
    return prisma.actionInboxItem.delete({
      where: { id, userId },
    });
  }
}

export class ReminderRepository {
  async create(userId: string, taskId: string, data: any) {
    return prisma.reminder.create({
      data: {
        userId,
        taskId,
        ...data,
      },
    });
  }

  async findPendingReminders() {
    return prisma.reminder.findMany({
      where: {
        sent: false,
        reminderTime: {
          lte: new Date(),
        },
      },
      include: {
        task: true,
        user: true,
      },
    });
  }

  async markAsSent(id: string) {
    return prisma.reminder.update({
      where: { id },
      data: { sent: true },
    });
  }
}

export class UserRepository {
  async findByEmail(email: string) {
    return prisma.user.findUnique({
      where: { email },
    });
  }

  async findById(id: string) {
    return prisma.user.findUnique({
      where: { id },
      select: {
        id: true,
        email: true,
        name: true,
        avatar: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  async create(data: { email: string; password: string; name: string }) {
    return prisma.user.create({
      data,
      select: {
        id: true,
        email: true,
        name: true,
        avatar: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }
}

